### ISSUE TITLE
display from the right of RecyclerView

### ISSUE THREAD

**Issue by mahramane** [brkckr/TableView#3] opened 2020-03-21 14:55 UTC
Is it possible to display from the right?
Help me please. It is very necessary

**Comment by brkckr** [comment] 2020-03-21 15:20
I may help if you can give me more details about what you want to do.

**Comment by mahramane** [comment] 2020-03-21 16:59
i use android:layoutDirection="rtl"

I want to show the horizontal scrollbar recyclerView from the right for the first time.

**Comment by mahramane** [comment] 2020-03-21 17:29
![photo_2020-03-21_21-58-21](https://user-images.githubusercontent.com/38125729/77232524-2a403d00-6bbf-11ea-84d4-936b4dcde8b5.jpg)

**Comment by brkckr** [comment] 2020-03-21 18:12
As far as I understand, you want RecyclerView to scroll right on the first boot.

manager.smoothScrollToPosition(rvClub, null,0);

manager : FixedGridLayoutManager manager;
rvClub : your RecyclerView.

state and the position are not important at this time. keep it null and 0.

**Comment by mahramane** [comment] 2020-03-21 18:43
Unfortunately it didn't work 😢

**Comment by brkckr** [comment] 2020-03-21 19:01
Then I have no other solution or idea. Good luck. Please let me know when you find the answer.

**Comment by mahramane** [comment] 2020-03-22 13:16
Hi
How can I use scrollHorizontallyBy in the FixedGridLayoutManager?

**Comment by brkckr** [comment] 2020-03-22 15:19
The parameter dx means the change in x coordinate. In your case, you want to move it in the opposite direction. which means dx must be a negative value. But I have no idea about other parameters of scrollHorizontallyBy. 

 Still, I am not sure if you use manager.smoothScrollToPosition(rvClub, null,0) correctly. 

```
 /**
     * Handles RecyclerView for the action
     */
    private void setUpRecyclerView()
    {
        clubAdapter = new ClubAdapter(MainActivity.this, clubList);

        FixedGridLayoutManager manager = new FixedGridLayoutManager();
        manager.setTotalColumnCount(1);
        rvClub.setLayoutManager(manager);
        rvClub.setAdapter(clubAdapter);
        rvClub.addItemDecoration(new DividerItemDecoration(MainActivity.this, DividerItemDecoration.VERTICAL));


        manager.smoothScrollToPosition(rvClub, null, 0);
    }
```
I got the following result from physical device, operating system Android 9.


![ezgif-3-275bb0cd79b1](https://user-images.githubusercontent.com/14269947/77253145-94152100-6c69-11ea-9c4f-21a7fed63971.gif)

**Comment by monsterbrain** [comment] 2020-05-15 12:17
Did you tried setReverseLayout(true) ? https://stackoverflow.com/questions/31728837/recyclerview-grow-element-from-right-to-left

**Comment by SaggamAnand** [comment] 2022-02-12 15:08
Hi, Could you please help me out? I am trying to add views dynamically (not fixed in size) for each recycler view item, but the problem is after adding views, it's not scrolling horizontally.  Attached screenshot for reference
![Scroll_issue](https://user-images.githubusercontent.com/67319951/153716701-73a18ed5-3ec1-4087-8f45-5f181e97ed33.png)
.

**Comment by brkckr** [comment] 2022-02-12 19:14
Hi,

Can you give 200dp width to each element you add to the row of the RecyclerView and tell me if it works?  The width of each row of the RecyclerView must be wrap_content. 

Do you have the 16th, 17th or 20th element in each row?

**Comment by SaggamAnand** [comment] 2022-02-14 07:53
Hi,
I tried to set a fixed height/width for the row item element, but still, it is not getting scroll. It gets scrolled when we have fixed views in each item of recycler view.

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    <TextView
        android:id="@+id/score_text_view"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:layout_centerInParent="true"
        android:gravity="center"
        android:textColor="@color/colorPrimaryDark" />

</RelativeLayout>
```

**Comment by brkckr** [comment] 2022-02-14 15:43
Then I have no other solution. Hope you can solve it.

**Closed as not planned** 2024-05-24 06:07 UTC
